version: '3.6'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./archivos:/home/airflow/monitor
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
   
    streamlit:
        build: frontend
        ports: 
            - "8501:8501"
        volumes: 
            - "./src:/app"
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "8081:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test123
    